apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <Base64 of CA. Take value from the kubeconfig used to create the ServiceAccount kubevirt-csi>
    server: <URL of cluster. E.g.https://api.crc.testing:6443. Take value from the kubeconfig used to create the ServiceAccount kubevirt-csi>
  name: infra-cluster
contexts:
- context:
    cluster: infra-cluster
    namespace: <optional, not used>
    user: kubevirt-csi
  name: only-context
current-context: only-context
kind: Config
preferences: {}
users:
- name: kubevirt-csi
  user:
    token: <use token from secret in ServiceAccount kubevirt-csi. Decode it from base64 (base64 -d)>
