apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: $CA_CRT
    server: $SERVER_URL
  name: infra-cluster
contexts:
- context:
    cluster: infra-cluster
    namespace: default
    user: kubevirt-csi
  name: only-context
current-context: only-context
kind: Config
preferences: {}
users:
- name: kubevirt-csi
  user:
    token: $TOKEN
